### PR TITLE
payment doc correction

### PR DESCRIPTION
**Pull request by ankitdas13**
[Capture payment (sdk audit)](https://docs.google.com/spreadsheets/d/1FwFHxOY994oS6jCmPd4ubdC4Itbr5QGaRg24_O6xj4U/edit#gid=0&range=A26): [update](url)

[Fetch all payment (sdk audit)](https://docs.google.com/spreadsheets/d/1FwFHxOY994oS6jCmPd4ubdC4Itbr5QGaRg24_O6xj4U/edit#gid=0&range=A27) : [update](url)

[Fetch payment (sdk audit)](https://docs.google.com/spreadsheets/d/1FwFHxOY994oS6jCmPd4ubdC4Itbr5QGaRg24_O6xj4U/edit#gid=0&range=A28): [update](https://github.com/razorpay/razorpay-go/blob/payment_doc_correction/documents/payment.md?plain=1#L141)

[Update a payment (sdk audit)](https://docs.google.com/spreadsheets/d/1FwFHxOY994oS6jCmPd4ubdC4Itbr5QGaRg24_O6xj4U/edit#gid=0&range=A30): [update](url)

[Fetch payment downtime details (sdk audit)](https://docs.google.com/spreadsheets/d/1FwFHxOY994oS6jCmPd4ubdC4Itbr5QGaRg24_O6xj4U/edit#gid=0&range=A33): [update](url)

[Fetch payment downtime by id (sdk audit)](https://docs.google.com/spreadsheets/d/1FwFHxOY994oS6jCmPd4ubdC4Itbr5QGaRg24_O6xj4U/edit#gid=0&range=A34): [update](url)

[Payment capture settiing (sdk audit)](https://docs.google.com/spreadsheets/d/1FwFHxOY994oS6jCmPd4ubdC4Itbr5QGaRg24_O6xj4U/edit#gid=0&range=A35): [update](url)

[Create payment json (sdk audit)](https://docs.google.com/spreadsheets/d/1FwFHxOY994oS6jCmPd4ubdC4Itbr5QGaRg24_O6xj4U/edit#gid=0&range=A36): [update](url)

### CODE REVIEW

**Review by sofiya02 — CHANGES_REQUESTED** [review]
1. Update a payment - update response customer_id, token_id and other parameter missing
2. Payment capture settings API - return Null and  add "," (comma)  on object close
3.  Create Payment Json - return NULL

**Comment by ankitdas13** [comment]
> 1. Update a payment - update response customer_id, token_id and other parameter missing
> 2. Payment capture settings API - return Null and  add "," (comma)  on object close
> 3. Create Payment Json - return NULL

1. response [updated](https://github.com/razorpay/razorpay-go/blob/payment_doc_correction/documents/payment.md?plain=1#L259)
2. [added comma ](https://github.com/razorpay/razorpay-go/blob/payment_doc_correction/documents/payment.md?plain=1#L400)
3. Need someone key who has access

**Review by sofiya02 — CHANGES_REQUESTED** [review]
Create Payment Json - add inverted comma to number "4111111111111111"

**Review by sofiya02 — APPROVED** [review]
LGTM

**Pull request merged**
